<?php

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

global $wpdb;

$table = $wpdb->prefix . 'pn_ai_chat_history';

$rows = $wpdb->get_results(
	"SELECT * FROM {$table} ORDER BY id DESC LIMIT 100"
);

?>

<div class="wrap">

	<h1>
		<?php esc_html_e( 'System Logs', 'pn-ai-agent' ); ?>
	</h1>

	<p class="description">
		<?php
		esc_html_e(
			'View recent AI conversations generated by your website.',
			'pn-ai-agent'
		);
		?>
	</p>

	<div class="pn-toolbar">

		<button
			type="button"
			class="button"
			onclick="location.reload();">

			<?php
			esc_html_e(
				'Refresh',
				'pn-ai-agent'
			);
			?>

		</button>

		<button
			type="button"
			class="button button-secondary"
			disabled>

			<?php
			esc_html_e(
				'Clear Logs (Pro)',
				'pn-ai-agent'
			);
			?>

		</button>

	</div>

	<table class="widefat striped">

		<thead>

			<tr>

				<th width="120">
					<?php esc_html_e( 'Role', 'pn-ai-agent' ); ?>
				</th>

				<th>
					<?php esc_html_e( 'Conversation', 'pn-ai-agent' ); ?>
				</th>

				<th width="180">
					<?php esc_html_e( 'Created', 'pn-ai-agent' ); ?>
				</th>

			</tr>

		</thead>

		<tbody>

		<?php if ( ! empty( $rows ) ) : ?>

			<?php foreach ( $rows as $row ) : ?>

				<?php

				$class = match ( $row->role ) {
					'user'      => 'pn-role-user',
					'assistant' => 'pn-role-assistant',
					default     => 'pn-role-system',
				};

	?>

				<tr>

					<td>

						<span class="pn-role <?php echo esc_attr( $class ); ?>">

							<?php echo esc_html( ucfirst( $row->role ) ); ?>

						</span>

					</td>

					<td>

						<?php
						echo nl2br(
							esc_html( $row->message )
						);
						?>

					</td>

					<td>

						<?php echo esc_html( $row->created_at ); ?>

					</td>

				</tr>

			<?php endforeach; ?>

		<?php else : ?>

			<tr>

				<td colspan="3">

					<?php
					esc_html_e(
						'No log entries found.',
						'pn-ai-agent'
					);
					?>

				</td>

			</tr>

		<?php endif; ?>

		</tbody>

	</table>

	<p class="description">

		<?php
		esc_html_e(
			'Showing the latest 100 log entries.',
			'pn-ai-agent'
		);
		?>

	</p>

</div>