<?php

declare(strict_types=1);

namespace PNAIAgent\Frontend;

class ChatWidget extends \WP_Widget {

	public function __construct() {

		parent::__construct(
			'pn_ai_chat_widget',
			__( 'PN AI Chat', 'pn-ai-agent' )
		);
	}

	public function widget( $args, $instance ): void {

		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core.
		echo $args['before_widget'];

		echo wp_kses_post( do_shortcode( '[pn_ai_chat]' ) );

		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core.
		echo $args['after_widget'];
	}

	public function form( $instance ): void {
		$title = $instance['title'] ?? __( 'PN AI Chat', 'pn-ai-agent' );

		?>
		<p>
			<label>
				<?php esc_html_e( 'Title:', 'pn-ai-agent' ); ?>
			</label>

			<input
				class="widefat"
				name="<?php echo esc_attr( $this->get_field_name( 'title' ) ); ?>"
				value="<?php echo esc_attr( $title ); ?>"
			>
		</p>
		<?php
	}

	public function update( $new_instance, $old_instance ): array {
		return array(
			'title' => sanitize_text_field( $new_instance['title'] ?? '' ),
		);
	}
}